---
apiVersion: v1
kind: Pod
metadata:
   name: postgres-db
   labels:
    app: mypgdb
    created_by: Vinnu2210
spec: 
   containers:     
    - name: postgres-container 
      image: postgres
      env:
       - name: POSTGRES_PASSWORD
         value: Vinnu@2210
       - name: POSTGRES_USER
         value: rootuser
       - name: POSTGRES_DB
         value: mydb
...
 
