---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  namespace: my-ns
  labels:
     app: httpd
     author: vinay
spec:
  containers:
   - name: httpd-container
     image: httpd
     ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: httpd-ip
 namespace: my-ns
spec:
 type: LoadBalancer
 selector:
  app: httpd
 ports:
  - port: 7777
    targetPort: 80
