---
apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
 labels:
  app: proxy
  author: Vinnu2210
spec:
 containers:
  - name: nginx-container
    image: nginx
    ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ip
spec:
 type: LoadBalancer
 selector:
  app: proxy
 ports:
 - port: 5050
   targetPort: 80
 
