apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
  labels:
     app: webserver
     author: Vinay
spec:
 replicas: 3
 template:
   metadata:
     name: httpd-pod
     labels:
         app: webserver
         author: vinay
   spec:
     containers:
       - name: httpd-container
         image: httpd
         ports:
           - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-ip
  labels:
   author: vinay
spec:
   type: LoadBalancer
   selector:
     app: webserver
   ports:
     - targetPort: 80
       port: 2222
...  
