---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: ngnix-rc
 labels:
  app: proxy
  author: vinay
spec:
  replicas: 4
  selector:
   matchLabels: 
    app: proxy
  template:
   metadata:
    labels:
     app: proxy
   spec:
    containers:
     - name: nginx-container
       image: nginx
       ports:
        - containerPort: 80
 
---
apiVersion: v1
kind: Service
metadata:
 name: nginx-ip
spec:
 type: LoadBalancer
 selector:
  app: proxy
 ports:
   - targetPort: 80
     port: 55
...   
