---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: tomcat-rs
  labels:
   app: appserver
   author: vinay
spec:
 replicas: 2
 selector:
  matchLabels:
    app: appserver
 template:
  metadata:
   labels:
    app: appserver
  spec:
   containers: 
    - name: tomcat-container
      image: tomee
      ports:  
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: tomcat-ip
spec:
 type: LoadBalancer
 selector: 
   app: appserver
 ports: 
  - targetPort: 8080
    port: 1001
...
 
