---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: proxy
    author: vinay  
spec:
  containers:
   - name: nginx-container
     image: nginx
     ports:
      - containerPort: 80
     resources:
       requests:
        cpu: 100m
        memory: 64M
       limits:
        cpu: 200m
        memory: 128M
...
