---
apiVersion: v1
kind: Service
metadata:
  name: my-sql
  labels:
    app: mydb
spec:
  clusterIP: None
  selector:
    app: mydb
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-sql
  labels:
    app: mydb
spec:
  serviceName: my-sql
  replicas: 3
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
        - name: mysql-container
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: vinnu2210
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: mysql-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
