---
apiVersion: v1
kind: Pod
metadata: 
  name: sql-pod
  labels:
    app: mydb
    created_by: Vinay
spec:
 containers:
  - name: sql-container
    image: mysql
    env:
     - name: MYSQL_ROOT_PASSWORD
       value: vinay2210
    volumeMounts:
      - name: sql-volume
        mountPath: lib/var/mysql
 volumes:
   - name: sql-volume
     emptyDir: {}
...
