---
apiVersion: v1
kind: Pod
metadata:
 name: redis-pod
 labels: 
  name: redisdb
  created_by: vinay
spec:
 containers:
  - name: redis-container
    image: redis
    volumeMounts:
     - name: myvolume
       mountPath: /data/redis
 volumes:
  - name: myvolume
    emptyDir: {}
...
