---
apiVersion: v1
kind: Pod
metadata:
 name: my-sql
 labels:
  app: my-db
spec:
 containers:
  -  name: sql-container
     image: mysql
     env:
      - name: MYSQL_ROOT_PASSWORD
        value: Vinay2210
     volumeMounts:
      - name: sql-volume
        mountPath: var/lib/mysql
 volumes:
  -  name: sql-volume
     persistentVolumeClaim:
       claimName: my-pvc
...
